# Simulaciones Monte-Carlo

In [ ]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
from pandas_datareader import data as pdr # Esta funci√≥n descarga datos a partir de fuentes distintas distintas a yfinance

In [ ]:
import yfinance as yf
yf.pdr_override()

In [ ]:
apple = pdr.get_data_yahoo("AAPL", start = "2022-10-24", end="2022-12-23")
apple

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-10-24,147.190002,150.229996,146.000000,149.449997,148.568634,75981900
2022-10-25,150.089996,152.490005,149.360001,152.339996,151.441605,74732300
2022-10-26,150.960007,151.990005,148.039993,149.350006,148.469238,88194300
2022-10-27,148.070007,149.050003,144.130005,144.800003,143.946060,109180200
2022-10-28,148.199997,157.500000,147.820007,155.740005,154.821548,164762400
2022-10-31,153.160004,154.240005,151.919998,153.339996,152.435684,97943200
2022-11-01,155.080002,155.449997,149.130005,150.649994,149.761551,80379300
2022-11-02,148.949997,152.169998,145.000000,145.029999,144.174698,93604600
2022-11-03,142.059998,142.800003,138.750000,138.880005,138.060974,97918500
2022-11-04,142.089996,142.669998,134.380005,138.380005,137.792130,140814800
2022-11-07,137.110001,139.149994,135.669998,138.919998,138.329819,83374600
2022-11-08,140.410004,141.429993,137.490005,139.500000,138.907364,89908500
2022-11-09,138.500000,138.550003,134.589996,134.869995,134.297028,74917800
2022-11-10,141.240005,146.869995,139.500000,146.869995,146.246033,118854000
2022-11-11,145.820007,150.009995,144.369995,149.699997,149.064026,93979700
2022-11-14,148.970001,150.279999,147.429993,148.279999,147.650055,73374100
2022-11-15,152.220001,153.589996,148.559998,150.039993,149.402573,89868300
2022-11-16,149.130005,149.869995,147.289993,148.789993,148.157883,64218300
2022-11-17,146.429993,151.479996,146.149994,150.720001,150.079681,80389400
2022-11-18,152.309998,152.699997,149.970001,151.289993,150.647263,74829600
2022-11-21,150.160004,150.369995,147.720001,148.009995,147.381210,58724100
2022-11-22,148.130005,150.419998,146.929993,150.179993,149.541977,51804100
2022-11-23,149.449997,151.830002,149.339996,151.070007,150.428207,58301400
2022-11-25,148.309998,148.880005,147.119995,148.110001,147.480789,35195900
2022-11-28,145.139999,146.639999,143.380005,144.220001,143.607315,69246000
2022-11-29,144.289993,144.809998,140.350006,141.169998,140.570267,83763800
2022-11-30,141.399994,148.720001,140.550003,148.029999,147.401123,111380900
2022-12-01,148.210007,149.130005,146.610001,148.309998,147.679932,71250400
2022-12-02,145.960007,148.000000,145.649994,147.809998,147.182068,65447400
2022-12-05,147.770004,150.919998,145.770004,146.630005,146.007080,68826400
2022-12-06,147.070007,147.300003,141.919998,142.910004,142.302872,64727200
2022-12-07,142.190002,143.369995,140.000000,140.940002,140.341248,69721100
2022-12-08,142.360001,143.520004,141.100006,142.649994,142.043976,62128300
2022-12-09,142.339996,145.570007,140.899994,142.160004,141.556061,76097000
2022-12-12,142.699997,144.500000,141.059998,144.490005,143.876160,70462700
2022-12-13,149.500000,149.970001,144.240005,145.470001,144.852005,93886200
2022-12-14,145.350006,146.660004,141.160004,143.210007,142.601608,82291200
2022-12-15,141.110001,141.800003,136.029999,136.500000,135.920105,98931900
2022-12-16,136.690002,137.649994,133.729996,134.509995,133.938568,160156900
2022-12-19,135.110001,135.199997,131.320007,132.369995,131.807632,79592600
2022-12-20,131.389999,133.250000,129.889999,132.300003,131.737946,77432800
2022-12-21,132.979996,136.809998,132.750000,135.449997,134.874573,85928000
2022-12-22,134.350006,134.559998,130.300003,132.229996,131.668243,77852100

## Vamos a calcular el crecimiento anual compuesto sobre las fechas dadas.

In [ ]:
apple["Adj Close"][-1:] # El argumento [-1] regresa el ultimo valor de la serie

Date
2022-12-22    131.668243
Name: Adj Close, dtype: float64

In [ ]:
crecimiento_total = apple["Adj Close"][1]/apple["Adj Close"][-1]
crecimiento_total

1.150175628490406

Anualizar porcentajes:

In [ ]:
tiempo_transcurrido = (apple.index[-1]-apple.index[0]).days
tiempo_transcurrido

59

In [ ]:
len(list(apple.index))

43

In [ ]:
crecimiento_compuesto = crecimiento_total**(43)-1
crecimiento_compuesto

409.0708702642962

In [ ]:
# Vamos a calcular la volatilidad de los rendimientos
volatilidad = apple["Adj Close"].pct_change().std()
volatilidad

0.027407151440380063

In [ ]:
volatilidad_total = volatilidad*math.sqrt(252) # 252**0.5
volatilidad_total

0.43507504113558804

In [ ]:
# Vamos a generar porcentajes de rendimiento diario
rendimientos_diarios = np.random.normal()